name: nhentai
description: Client for nhentai.net undocumented APIs written in Dart.
version: 1.0.0-dev.9
homepage: https://github.com/Zekfad/nhentai_dart
repository: https://github.com/Zekfad/nhentai_dart
issue_tracker: https://github.com/Zekfad/nhentai_dart/issues
# documentation: https://pub.dev/documentation/nhentai/latest/

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  zekfad_lints: ^1.1.0
  test: ^1.16.0
dependencies: 
  meta: ^1.8.0
  universal_io: ^2.0.4
